version: '3'

services:
  server:
    build: .
    ports:
    - 5000:5000
    volumes:
    - data:/app/instance
    environment:
      FLASK_APP: 'weatherAggregator'
      FLASK_RUN_HOST: '0.0.0.0'
    command: ["run"]

volumes:
  data: